syntax = "proto3";

package code_execution;

import "google/protobuf/struct.proto";

service CodeExecution {
    rpc TestConnection (TestConnectionRequest) returns (TestConnectionResponse);
    rpc ExecuteCode (ExecuteCodeRequest) returns (ExecuteCodeResponse);
}

message TestConnectionRequest {
    string message = 1;
}

message TestConnectionResponse {
    string message = 1;
}

message ExecuteCodeRequest {
    enum Language {
        PYTHON = 0;
        JAVASCRIPT = 1;
        JAVA = 2;
        C = 3;
        CPP = 4;
    }
    Language language = 1;
    string version = 2;
    string code = 3;
    repeated string stdin = 4;
}

message ExecuteCodeResponse {
    repeated string output = 1;
    repeated string stdout = 2;
    repeated string stderr = 3;
}