syntax = "proto3";

package code_execution;

import "google/protobuf/struct.proto";

service CodeExecution {
    rpc TestConnection (TestConnectionRequest) returns (TestConnectionResponse);
    rpc ExecuteCode (ExecuteCodeRequest) returns (ExecuteCodeResponse);
}

message TestConnectionRequest {
    string message = 1;
}

message TestConnectionResponse {
    string message = 1;
}

message ExecuteCodeRequest {
    enum Language {
        PYTHON = 0;
        JAVASCRIPT = 1;
        JAVA = 2;
        C = 3;
        CPP = 4;
    }
    string request_id = 1;
    Language language = 11;
    string version = 12;
    string code = 13;
    repeated string stdin = 14;
}

message ExecuteCodeResponse {
    string request_id = 1;
    repeated string output = 11;
    repeated string stdout = 12;
    repeated string stderr = 13;
}